### ISSUE TITLE
Incorrect IfcColourRgbList serialization

### ISSUE THREAD

**Issue by UsoltsevaM** [ifcquery/ifcplusplus#181] opened 2020-05-19 15:18 UTC
Hello,

We found a problem with serialization of IfcColourRgbList. It is serialized as empty container IFCCOLOURRGBLIST(), while according to IFC documentation it should be a list of colors, where each color is defined by three normalized ratios (RGB), e.g. IFCCOLOURRGBLIST(((1.,0.,0.),(0.,1.,0.),(0.,0.,1.))). 

If I'm not mistaken IfcColourRgbList::m_ColourList is not taken into account in IfcColourRgbList::getStepLine() - https://github.com/ifcquery/ifcplusplus/blob/master/IfcPlusPlus/src/ifcpp/IFC4/lib/IfcColourRgbList.cpp#L34.

Could it be fixed please?

**Comment by ifcquery** [comment] 2020-05-20 10:40
Hi, the issue is fixed with latest commit

**Closed by ifcquery** 2020-05-20 10:40 UTC
